# fly.toml app configuration file generated for ismygem-online on 2023-09-28T18:30:48-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ismygem-online-worker"
primary_region = "sjc"

[processes]
  worker = "celery -A server.worker worker --loglevel=INFO"