CREATE TABLE IF NOT EXISTS emails (
  id BINARY(16) PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  token VARCHAR(255),
  verified BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS urls (
  id BINARY(16) PRIMARY KEY,
  url VARCHAR(1024) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS schedules (
  id BINARY(16) PRIMARY KEY,
  email_id INTEGER NOT NULL,
  url_id INTEGER NOT NULL,
  every_secs INTEGER NOT NULL,
  last_failure_timestamp TIMESTAMP
);