CREATE TABLE IF NOT EXISTS emails (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  verified BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS urls (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  url VARCHAR(1024) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS schedules (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  email_id INTEGER NOT NULL,
  url_id INTEGER NOT NULL,
  every_secs INTEGER NOT NULL
);