name: Python CI
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.x'
          architecture: 'x64'

      - name: Install depenencies
        run: |
        python -m pip install --upgrade pip pipenv
        pipenv install

      - name: Run tests
        run: pipenv run pytest
