name: Python CI
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_DATABASE: gem_test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=8s --health-timeout=2s --health-retries=4

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.x'
          architecture: 'x64'

      - name: Copy .env.ci
        run: cp .env.ci .env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install -d

      - name: Run tests
        run: pipenv run pytest
